package com.ewansr.www.koobenapp;

/**
 * Created by Sam on 09/07/16.
 */
public enum KoobenExceptionCode {
    ITEM_FOUND, ITEM_NOT_FOUND,
    ITEM_CREATED, ITEM_NOT_CREATED, ITEM_ALREADY_EXISTS,
    ITEM_UPDATED, ITEM_NOT_UPDATED,
    ITEM_DELETED, ITEM_NOT_DELETED,

    ITEMS_FOUND, ITEMS_NOT_FOUND,
    ITEMS_EMPTY,

    UNKNOWW, INVALID_VALUES
}
